# * spam classifier *

In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [43]:
import nltk

# 1. loading the dataset

In [44]:
# import pandas as pd
spam_data = pd.read_csv("/home/ramchowdary/Desktop/spam classifier/smsspamcollection/SMSSpamCollection",sep='\t')

In [45]:
spam_data.head(5)

ham  \
0   ham   
1  spam   
2   ham   
3   ham   
4  spam   

  Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...  
0                      Ok lar... Joking wif u oni...                                                               
1  Free entry in 2 a wkly comp to win FA Cup fina...                                                               
2  U dun say so early hor... U c already then say...                                                               
3  Nah I don't think he goes to usf, he lives aro...                                                               
4  FreeMsg Hey there darling it's been 3 week's n...

# -> adding the column names to that data

In [46]:
spam_data = pd.read_csv("/home/ramchowdary/Desktop/spam classifier/smsspamcollection/SMSSpamCollection",sep='\t',names=['label','msg'])
# names is used to adding the column names 

In [47]:
spam_data.head()

label                                                msg
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

# 2. data_cleaning

In [49]:
# import required libraries
import re

In [50]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

# -> stop_words

In [51]:
# without these words sentence don't have any meaning
# load the english stop_words from the nltk.
from nltk.corpus import stopwords

# ->stemming

In [52]:
from nltk.stem.porter import PorterStemmer as ps

In [53]:
nltk.download("stopwords")

[nltk_data] Error loading stopwords: <urlopen error [Errno -2] Name or
[nltk_data]     service not known>


False

* -> create the new corpus

In [58]:
# create the new data corpus by applying the data preprocessing OR cleaning
new_corpus=[]
ps = PorterStemmer()# with out this stmt gives the positional argument.
for i in range(0,len(spam_data)):
    review = re.sub('[^a-zA-Z]',' ',spam_data['msg'][i])
    review = review.lower()
    review = review.split()
    review =[ps.stem(j) for j in review if not j in stopwords.words("english")]
    review = ' '.join(review)
    new_corpus.append(review)    

# 3.converting words into vectors

In [ ]:
# techniques


# -> bag of words

In [59]:
# importing required libraries
from sklearn.feature_extraction.text import CountVectorizer

In [61]:
vector = CountVectorizer(max_features=1500)# take required no of features based on ur system
X = vector.fit_transform(new_corpus).toarray()
# independend variable is ready

In [63]:
# dependend variable or label data.
Y = pd.get_dummies(spam_data['label'])

In [64]:
Y.head()

ham  spam
0    1     0
1    1     0
2    0     1
3    1     0
4    1     0

In [76]:
spam_data['label'].head(5)

0     ham
1     ham
2    spam
3     ham
4     ham
Name: label, dtype: object

In [77]:
# select any one of the column either spam column or ham column.

In [78]:
Y = Y.iloc[:,1].values

# 4.MODELS

In [79]:
# import required library to the model selection.
from sklearn.model_selection import train_test_split


In [80]:
# divide the data into train and test data
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.70,random_state = 100)


# ->train the model

In [81]:
# iam using the Navie Bayes classifier
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()


In [82]:
print(x_train)

[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]


In [83]:
print(y_train)

[0 0 0 ..., 0 0 0]


In [84]:
spam_detect_model = model.fit(x_train,y_train)

 -> predicting the model with test data

In [85]:
y_predict = spam_detect_model.predict(x_test)

# 5.METRICS

In [87]:
# 
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_predict)

array([[3324,   49],
       [  33,  495]])

In [91]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predict)

0.97897974878236349

In [93]:
from sklearn.metrics import roc_curve
roc_curve(y_test,y_predict)

(array([ 0.        ,  0.01452713,  1.        ]),
 array([ 0.    ,  0.9375,  1.    ]),
 array([2, 1, 0]))